config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    # don't need extra comma
    omniauth_callbacks: "omniauth_callbacks"
  }

  # landing_page#index
  root "landing_page#landing"

  resources :diet_types
  resources :ingredients

  # can use `resources :select_diet, only [:edit, :update]`
  get 'select_diet', to: 'select_diet#edit'
  patch 'select_diet', to: 'select_diet#update'

  # can use `resources :compliances` if you follow standard CRUD approach
  get "/food" => "compliance#food"
  get "/compliance" => "compliance#check_compliance"
end

app/controllers/diet_types_controller.rb
class DietTypesController < ApplicationController
  before_action :set_diet_type, only: %i[ show edit update destroy ]

  def index
    @diet_types = DietType.all
    authorize @diet_types
  end

  def show
  end

  def new
    @diet_type = DietType.new
  end

  def edit
  end

  def create
    @diet_type = DietType.new(diet_type_params)

    respond_to do |format|
      if @diet_type.save
        format.html { redirect_to diet_type_url(@diet_type), notice: "Diet type was successfully created." }
        format.json { render :show, status: :created, location: @diet_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @diet_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @diet_type.update(diet_type_params)
        format.html { redirect_to diet_type_url(@diet_type), notice: "Diet type was successfully updated." }
        format.json { render :show, status: :ok, location: @diet_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @diet_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @diet_type.destroy!

    respond_to do |format|
      format.html { redirect_to diet_types_url, notice: "Diet type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_diet_type
      @diet_type = DietType.find(params[:id])
      authorize @diet_type
    end

    def diet_type_params
      params.require(:diet_type).permit(:name)
    end
end

app/views/diet_types/_diet_type.html.erb
<div id="<%= dom_id diet_type %>">
  <p>
    <strong>Name:</strong>
    <%= diet_type.name %>
  </p>

</div>

app/views/diet_types/_form.html.erb
<%= form_with(model: diet_type) do |form| %>
  <% if diet_type.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(diet_type.errors.count, "error") %> prohibited this diet_type from being saved:</h2>

      <ul>
        <% diet_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div class= "btn">
    <%= form.submit %>
  </div>
<% end %>

app/views/diet_types/edit.html.erb
<h1>Editing diet type</h1>

<%= render "form", diet_type: @diet_type %>

<br>

<div>
  <%= link_to "Show this diet type", @diet_type %> |
  <%= link_to "Back to diet types", diet_types_path %>
</div>

app/views/diet_types/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Diet types</h1>

<div id="diet_types">
  <% @diet_types.each do |diet_type| %>
    <%= render diet_type %>
    <p>
      <%= link_to "Show this diet type", diet_type %>
    </p>
  <% end %>
</div>

<%= link_to "New diet type", new_diet_type_path %>

app/views/diet_types/new.html.erb
<h1>New diet type</h1>

<%= render "form", diet_type: @diet_type %>

<br>

<div>
  <%= link_to "Back to diet types", diet_types_path %>
</div>

app/views/diet_types/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @diet_type %>

<div>
  <%= link_to "Edit this diet type", edit_diet_type_path(@diet_type) %> |
  <%= link_to "Back to diet types", diet_types_path %>

  <%= button_to "Destroy this diet type", @diet_type, method: :delete %>
</div>