config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    # don't need extra comma
    omniauth_callbacks: "omniauth_callbacks"
  }

  # landing_page#index
  root "landing_page#landing"

  resources :diet_types
  resources :ingredients

  # can use `resources :select_diet, only [:edit, :update]`
  get 'select_diet', to: 'select_diet#edit'
  patch 'select_diet', to: 'select_diet#update'

  # can use `resources :compliances` if you follow standard CRUD approach
  get "/food" => "compliance#food"
  get "/compliance" => "compliance#check_compliance"
end

app/views/shared/_cdn_assets.html.erb
<!-- Connect Bootstrap CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css">

<!-- Connect Bootstrap JavaScript and its dependencies -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>

<!-- Connect Font Awesome -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/js/all.min.js"></script>

app/views/shared/_flash.html.erb
<div class="alert alert-<%= css_class %> alert-dismissible fade show my-4" role="alert">
  <%= message %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-cream" role="navigation" aria-label="Main navigation">
  <div class="container">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "SafeEats Logo.png", alt: "SafeEats Logo", class: "img-fluid", style: "max-height: 50px;" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% if user_signed_in? %>
        <ul class="navbar-nav me-left" role="menubar">
          <li class="nav-item" role="none">
            <%= link_to "Diet", select_diet_path, class: "nav-link", role: "menuitem" %>
          </li>
        </ul>
        <ul class="navbar-nav me-left" role="menubar">
          <li class="nav-item" role="none">
            <%= link_to "Ingredients", food_path, class: "nav-link", role: "menuitem" %>
          </li>
        </ul>
      <% end %>

      <ul class="navbar-nav ms-auto" role="menubar">
        <% if user_signed_in? %>
          <li class="nav-item dropdown" role="none">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">
              <%= current_user.username %>
            </a>
            <div class="dropdown-menu" role="menu">
              <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item", role: "menuitem" %>
              <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item", role: "menuitem" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item" role="none">
            <%= link_to "Sign in", new_user_session_path, class: "nav-link", role: "menuitem" %>
          </li>

          <li class="nav-item" role="none">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link", role: "menuitem" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>