config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    # don't need extra comma
    omniauth_callbacks: "omniauth_callbacks"
  }

  # landing_page#index
  root "landing_page#landing"

  resources :diet_types
  resources :ingredients

  # can use `resources :select_diet, only [:edit, :update]`
  get 'select_diet', to: 'select_diet#edit'
  patch 'select_diet', to: 'select_diet#update'

  # can use `resources :compliances` if you follow standard CRUD approach
  get "/food" => "compliance#food"
  get "/compliance" => "compliance#check_compliance"
end

app/models/ingredient.rb
# == Schema Information
#
# Table name: ingredients
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  diet_id    :integer
#
class Ingredient < ApplicationRecord
  belongs_to :diet_type, required: true, class_name: "DietType", foreign_key: "diet_id"
end

app/controllers/ingredients_controller.rb
# is this needed?
require "csv"
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: %i[ show edit update destroy ]
  # might be nice to authorize here

  def index
    @ingredients = Ingredient.all
    authorize @ingredients
  end

  def show
    authorize @ingredient
  end

  def new
    @ingredient = Ingredient.new
    authorize @ingredient
  end

  def edit
    authorize @ingredient
  end

  def create
    # @ingredient is nil here
    # authorize @ingredient
    @ingredient = authorize Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to ingredient_url(@ingredient), notice: "Ingredient was successfully created." }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

def update
  authorize @ingredient

  respond_to do |format|
    if @ingredient.update(ingredient_params)
      format.html { redirect_to ingredient_url(@ingredient), notice: "Ingredient was successfully updated." }
      format.json { render :show, status: :ok, location: @ingredient }
    else
      format.html { render :edit, status: :unprocessable_entity }
      format.json { render json: @ingredient.errors, status: :unprocessable_entity }
    end
  end
end

  def destroy
    authorize @ingredient
    @ingredient.destroy!

    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: "Ingredient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    def ingredient_params
      params.require(:ingredient).permit(:name, :vegetarian, :vegan)
    end
end

app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient) do |form| %>
  <% if ingredient.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
        <% ingredient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :vegetarian, style: "display: block" %>
    <%= form.check_box :vegetarian %>
  </div>

  <div>
    <%= form.label :vegan, style: "display: block" %>
    <%= form.check_box :vegan %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/ingredients/_ingredient.html.erb
<div id="<%= dom_id ingredient %>">
  <p>
    <strong>Name:</strong>
    <%= ingredient.name %>
  </p>
</div>

app/views/ingredients/edit.html.erb
<h1>Editing ingredient</h1>

<%= render "form", ingredient: @ingredient %>

<br>

<div>
  <%= link_to "Show this ingredient", @ingredient %> |
  <%= link_to "Back to ingredients", ingredients_path %>
</div>

app/views/ingredients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Ingredients</h1>

<div id="ingredients">
  <% @ingredients.each do |ingredient| %>
    <%= render ingredient %>
    <p>
      <%= link_to "Show this ingredient", ingredient %>
    </p>
  <% end %>
</div>

<%= link_to "New ingredient", new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New ingredient</h1>

<%= render "form", ingredient: @ingredient %>

<br>

<div>
  <%= link_to "Back to ingredients", ingredients_path %>
</div>

app/views/ingredients/show.html.erb
<div>
  <div>
    <h1>
      Ingredient #<%= @the_ingredient.id %> details
    </h1>

    <div>
      <div>
        <a href="/ingredients">
          Go back
        </a>
      </div>

      <div>
        <a href="/delete_ingredient/<%= @the_ingredient.id %>">
          Delete ingredient
        </a>
      </div>
    </div>

    <dl>
      <dt>
        Name
      </dt>
      <dd>
        <%= @the_ingredient.name %>
      </dd>

      <dt>
        Created at
      </dt>
      <dd>
        <%= time_ago_in_words(@the_ingredient.created_at) %> ago
      </dd>

      <dt>
        Updated at
      </dt>
      <dd>
        <%= time_ago_in_words(@the_ingredient.updated_at) %> ago
      </dd>
    </dl>
  </div>
</div>

<hr>


<div>
  <div>
    <h2>
      Edit ingredient
    </h2>

    <form action="/modify_ingredient/<%= @the_ingredient.id %>"  method="post" >
      <div>
        <label for="name_box">
          Name
        </label>

        <input type="text" id="name_box" name="query_name" value="<%= @the_ingredient.name %>">
      </div>

      <button>
        Update ingredient
      </button>
    </form>
  </div>
</div>

<hr>