config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    # don't need extra comma
    omniauth_callbacks: "omniauth_callbacks"
  }

  # landing_page#index
  root "landing_page#landing"

  resources :diet_types
  resources :ingredients

  # can use `resources :select_diet, only [:edit, :update]`
  get 'select_diet', to: 'select_diet#edit'
  patch 'select_diet', to: 'select_diet#update'

  # can use `resources :compliances` if you follow standard CRUD approach
  get "/food" => "compliance#food"
  get "/compliance" => "compliance#check_compliance"
end

app/controllers/compliance_controller.rb
# maybe CompliancesController with a 'Compliance' model
# this way you can track all the compliances that users are checking
# and you'll have a more standard CRUD actions: new, create, show, etc.
class ComplianceController < ApplicationController
  # good before_action 👍
  before_action :check_diet_id, only: [:food, :check_compliance]

  # new
  def food
  end

  # create
  def check_compliance
    ingredients_param = params["ingredients"]
    @ingredients = ingredients_param.present? ? ingredients_param.split(',').map(&:strip) : []

    if @ingredients.empty?
      redirect_to food_path, { :alert => "Please enter ingredients before proceeding." }
    else
      # might be more readable to have a strong domain driven approach `current_user.can_eat? @ingredients`
      service = FoodComplianceService.new(current_user, @ingredients)
      @compliant = service.call

      if @compliant
        render "compliance/can_eat"
      else
        render "compliance/cant_eat"
      end
    end
  end

  private

  def check_diet_id
    if current_user.diet_id.blank?
      redirect_to select_diet_path, alert: "Please select a diet type before choosing a meal."
    end
  end
end

app/views/compliance/_form.html.erb
<%= form_with url: compliance_path, method: :get do |form| %>
  <div class="mb-3">
    <%= form.label :ingredients, "Enter Barcode or Ingredients", class: "pb-3 fs-3" %>
    <%# nice regex %>
    <%= form.text_field :ingredients, class: "form-control", placeholder: "e.g. sugar, salt, flour", pattern: "[a-zA-Z0-9, ]+", title: "Please enter valid ingredients. Only letters, numbers, and commas are allowed." %>
  </div>
  <div class="text-center">
    <%= form.submit "Submit", class: "btn btn-sand" %>
  </div>
<% end %>

app/views/compliance/can_eat.html.erb
<h1 class= "can-eat compliance-result p-4">Congrats!!!<br>You can eat :)</h1>

app/views/compliance/cant_eat.html.erb
<h1 class= " cant-eat compliance-result p-4">Sorry<br>You can't eat :(</h1>

app/views/compliance/food.html.erb
<h1 class="title">Scan it, Eat it, Love it!</h1>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card shadow-sm border-light">
        <div class="card-body mb-2">
          <%= render partial: "form" %>
        </div>
      </div>
    </div>
  </div>
</div>